% opens a figure and sets the defaults for position and size
function [hFig] = SetupFigure_220724(FigSizeInch)
    FigSize = [3.5 5];
    if nargin > 0 
        FigSize = FigSizeInch;
    end
    paperSize = FigSize+2;%[8.5 11];
    paperPosition = [1 1 FigSize];
    %
    hFig = figure;
    set(hFig,...
        'DefaultAxesFontSize',12,...
        'DefaultLineLineWidth',1,...
        'PaperUnits','inch',...
        'Color','w',...
        'InvertHardcopy','off',...
        'PaperSize',paperSize,...
        'GraphicsSmoothing','on',...
        'PaperPosition',paperPosition)
    colormap('jet');
    hFig.Units = 'inch';
    hFig.Position = [1 1 FigSize];
    hFig.Resize = 'off';
end

